### ISSUE TITLE
Version 1.0 uses old-style hashrockets in schema.rb

### ISSUE THREAD

**Issue by swrobel** [SchemaPlus/schema_plus_core#10]
I just ran `rake db:migrate` after updating to 1.0 from 0.6.2 and noticed that many more lines of the file were changed than I was expecting. I discovered that it converted the Ruby 1.9+ hash syntax to oldschool hashrockets, and not particularly nicely-formatted ones, at that, for example `null: false` became `:null=>false`.  Is there any reason that this change was made? It doesn't seem like this gem attempts to support Ruby 1.8, so I don't see why the regression to the old syntax.

**Comment by ronen** [comment]
The hashrockets are generated by MRI itself when it formats a hash to a string. This change is because of a bit of bug fixing/API improvement that cleaned up some option handling and replaced some custom output formatting that wasn't as robust (albeit was prettier when it worked).

I agree it's unfortunate, I also prefer the output the way it was--but I couldn't really justify the extra time and extra coding (with possible introduction of bugs) to write a custom hash formatter.

**Comment by swrobel** [comment]
Thanks for the quick response. Appreciate the hard work!

**Comment by ronen** [comment]
No prob.  Thanks for caring about schema_plus!
