### ISSUE TITLE
Rails 5.1 support

### ISSUE THREAD

**Issue by shimms** [SchemaPlus/schema_plus_core#19]
Wondering if someone who appreciates the intricacies of ActiveRecord a bit more can advise on the impact of allowing the dependency on `active_record` to support 5.1 instead of the current `"~> 5.0"`.

Making the change to gemspec is easy, but I'm not familiar enough about all the other SchemaPlus gems that rely on core to appreciate what unintended side affects that would have.

We're using `schema_auto_foreign_keys` in our project and are in the process of upgrading to 5.1, with this being the last incompatibility we're hitting.

**Comment by ronen** [comment]
Dependency-wise, `"~> 5.0"` would allow 5.1 so that's not an issue.

But still the code needs to be upgraded to work with 5.1.  I added 5.1 to `schema_dev.yml` and ran the specs, and there are failures.  The good news is that only 6 out of 53 tests failed, and they all seem clustered around one thing -- how AR implements `t.references`.  (And actually some of those failures look like they were introduced in AR 5.0.3).   [In fact, it's possible that the specs themselves simply need to change; this may be a case where schema_plus_core is simply setting a flag to report on what AR is doing, and in 5.1 AR doesn't do that any more.  So all that may need changing is the expectation of that flag value.)

Once that's done, I'd expect some changes are likely to be needed in the code for `schema_plus_foreign_keys` and `schema_auto_foreign_keys`, especially since it seems AR 5.1 has more support for foreign keys.

The bad news is that I myself don't have time to look into it right now.  Unfortunately I'm not currently actively using Rails for any of my work.  If you (or somebody else out there in github-land!) can look into it that'd be great.

**Comment by elsurudo** [comment]
Just as a data point, I've created my own fork just so I could use it with 5.1 (I simply updated the gemspec to allow 5.1), and it's been working without issue so far. Obviously, this specs still need looking into, but thought I would share.

**Comment by ronen** [comment]
Closing this -- version 2.1.0 which support Rails 5.1 is now released.  Many thanks to @iagopiimenta
